const collections = [
  {
    id: "1",
    name: "Milgauss 116400GV 'Rolex Milgauss 6541 Tribute'",
    price: "£15,495",
    desc: "Presented in excellent condition is this stunning example of a 2015 Rolex Milgauss 116400GV ‘Tribute to 6541’, customised by Hercules Watch Co. The watch features a 40mm stainless steel case, black honeycomb dial, red lightning bolt second hand, yellow hour markers, rotating bezel with black insert and is coupled to a stainless steel Oyster bracelet. Having been professionally tested for condition and accuracy, it’s deemed to be running perfectly, ready for its new, very lucky owner.",
    image: "/products/Milgauss116400GV/2015-Rolex-CM1732-02.jpg",
    link: "https://bloombarwatches.com/product/rolex-milgauss-116400gv-tribute-to-6541-hercules-watch-co/",
    additional: [
      { Year: "2015" },
      { Box: "Yes" },
      { Papers: "Yes" },
      { "Case Size": "40mm" },
      { "Strap Material": "Steel" },
      { Movement: "Automatic" },
      { Condition: "10/10 Excellent" },
      { "Case Material": "Steel" },
      { Model: "Milgauss 116400GV 'Rolex Milgauss 6541 Tribute'" },
      { "Bloombar Ref": "CM1732" },
    ],
    images: [
      "/products/Milgauss116400GV/2015-Rolex-CM1732-02.jpg",
      "/products/Milgauss116400GV/2015-Rolex-CM1732-03.jpg",
      "/products/Milgauss116400GV/2015-Rolex-CM1732-04.jpg",
      "/products/Milgauss116400GV/2015-Rolex-CM1732-05.jpg",
      "/products/Milgauss116400GV/2015-Rolex-CM1732-06.jpg",
      "/products/Milgauss116400GV/2015-Rolex-CM1732-1087.jpg",
      "/products/Milgauss116400GV/2015-Rolex-CM1732-1088.jpg",
      "/products/Milgauss116400GV/2015-Rolex-CM1732-1090.jpg",
    ],
  },
  {
    id: "2",
    name: "Air-King 116900 'Hunter' by Hercules Watch Co",
    price: "£15,495",
    desc: "Presented in excellent and stickered condition is this intriguing example of a 2018 Rolex Air-King 116900 ‘Hunter’, customised by Hercules Watch Co. The watch features a 40mm black stainless steel case, black dial with quarter Arabic numerals and a ‘Hunter’ inscription in green. This unique timepiece bears detailed engravings of various animals on a brushed stainless steel Oyster bracelet. Having been professionally tested for condition and accuracy, it’s deemed to be running perfectly, ready for its new, lucky owner.",
    image: "/products/Air-King116900/2018-Rolex-CM1733-02.webp",
    link: "https://bloombarwatches.com/product/rolex-air-king-116900-hunter-hercules-watch-co/",
    additional: [
      { Year: "2018" },
      { Box: "Yes" },
      { Papers: "Yes" },
      { "Case Size": "40mm" },
      { "Strap Material": "Steel" },
      { Movement: "Automatic" },
      { Condition: "10/10 Excellent/Stickered" },
      { "Case Material": "Steel" },
      { Model: "Air-King 116900 'Hunter' by Hercules Watch Co" },
      { "Bloombar Ref": "CM1733" },
    ],
    images: [
      "/products/Air-King116900/2018-Rolex-CM1733-02.webp",
      "/products/Air-King116900/2018-Rolex-CM1733-03.webp",
      "/products/Air-King116900/2018-Rolex-CM1733-04.webp",
      "/products/Air-King116900/2018-Rolex-CM1733-05.webp",
      "/products/Air-King116900/2018-Rolex-CM1733-06.webp",
      "/products/Air-King116900/2018-Rolex-CM1733-1120.webp",
      "/products/Air-King116900/2018-Rolex-CM1733-1121.webp",
      "/products/Air-King116900/2018-Rolex-CM1733-1123.webp",
    ],
  },
  {
    id: "3",
    name: "Oyster Perpetual 41 124300 'Dragon Among Men'",
    price: "£14,995",
    desc: "This special example of a Rolex Oyster Perpetual 41 124300 has been customised by Hercules Watch Co and created to celebrate the 2024 Chinese Year of the Dragon. The watch features a 41mm stainless steel case, champagne dial, smooth stainless steel bezel and is coupled to a stainless steel Oyster bracelet. This clean champagne dial shows a fine engraving of a dragon with red eyes and the hour markers are in matching red, too. The case back of this stunning timepiece also bears a dragon motif. As a final touch, the clasp of the Oyster bracelet has been finished off with an inscription in mandarin, which translates to ‘Dragon Among Men’.",
    image: "/products/OysterPerpetual/Rolex-CM1479-02.webp",
    link: "https://bloombarwatches.com/product/rolex-oyster-perpetual-41-124030-dragon-among-men/",
    additional: [
      { Year: "-" },
      { Box: "Yes" },
      { Papers: "Yes" },
      { "Case Size": "41mm" },
      { "Strap Material": "Steel" },
      { Movement: "Automatic" },
      { Condition: "Customised" },
      { "Case Material": "Steel" },
      { Model: "Oyster Perpetual 41 124300 'Dragon Among Men'" },
      { "Bloombar Ref": "CM1479" },
    ],
    images: [
      "/products/OysterPerpetual/Rolex-CM1479-02.webp",
      "/products/OysterPerpetual/Rolex-CM1479-03.webp",
      "/products/OysterPerpetual/Rolex-CM1479-04.webp",
      "/products/OysterPerpetual/Rolex-CM1479-05.webp",
      "/products/OysterPerpetual/Rolex-CM1479-06.webp",
      "/products/OysterPerpetual/Rolex-CM1479-505.webp",
      "/products/OysterPerpetual/Rolex-CM1479-506.webp",
      "/products/OysterPerpetual/Rolex-CM1479-507.webp",
    ],
  },

  {
    id: "4",
    name: "Datejust II 116334 'Hercules Watch Co'",
    price: "£12,950",
    desc: "Presented in excellent condition is this beautiful example of a 2013 Rolex Datejust II 116334, customised by Hercules Watch Co. The watch features a 41mm stainless steel case, customised ‘Tiffany’ blue dial with diamond hour markers, 18K white gold fluted bezel and is coupled to a stainless steel Oyster bracelet. Having been professionally tested for condition and accuracy, it’s deemed to be running perfectly, ready for its new, lucky owner. Serviced by Rolex in July, 2021. The watch is supplied with its Rolex box, green leather wallet, manuals, 2x swing tags and warranty card dated Q1 2013 (Germany). The watch will be sold with a 36-month Hercules Watch Co warranty from date of sale (Terms & Conditions apply).",
    image: "/products/Datejust/2013-Rolex-CM957-0002.jpg",
    link: "https://bloombarwatches.com/product/rolex-datejust-ii-116334-hercules-watch-co-2/",
    additional: [
      { Year: "2013" },
      { Box: "Yes" },
      { Papers: "Yes" },
      { "Case Size": "41mm" },
      { "Strap Material": "Steel" },
      { Movement: "Automatic" },
      { Condition: "Customised" },
      { "Case Material": "Steel" },
      { Model: "Datejust II 116334 'Hercules Watch Co'" },
      { "Bloombar Ref": "CM957" },
    ],
    images: [
      "/products/Datejust/2013-Rolex-CM957-0002.jpg",
      "/products/Datejust/2013-Rolex-CM957-0003.jpg",
      "/products/Datejust/2013-Rolex-CM957-0004.jpg",
      "/products/Datejust/2013-Rolex-CM957-0005.jpg",
      "/products/Datejust/2013-Rolex-CM957-0006.jpg",
      "/products/Datejust/2013-Rolex-CM957-056.jpg",
      "/products/Datejust/2013-Rolex-CM957-057.jpg",
      "/products/Datejust/2013-Rolex-CM957-059.jpg",
    ],
  },

  {
    id: "5",
    name: "Submariner Date 116610LN 'Hercules Watch Co'",
    price: "£18,495",
    desc: "Presented in excellent condition is this outstanding example of a 2019 Rolex Submariner Date 116610LN, customised by Hercules Watch Co. The watch features a 40mm black DLC coated case, black dial with white luminescent hour markers, black DLC coated bezel with black ceramic insert and is coupled to a black DLC coated Oyster bracelet. Having been professionally tested for condition and accuracy, it’s deemed to be running perfectly, ready for its new, very lucky owner. The watch is supplied with its original Rolex box, green leather wallet, manuals, 2x swing tags and warranty card dated Q3 2019 (UK supplied). The watch will be sold with a 36-month Hercules Watch Co warranty from date of sale (Terms & Conditions apply).",
    image: "/products/Submariner/2019-Rolex-CM885-02.webp",
    link: "https://bloombarwatches.com/product/rolex-submariner-date-116610ln-hercules-watch-co-3/",
    additional: [
      { Year: "2019" },
      { Box: "Yes" },
      { Papers: "Yes" },
      { "Case Size": "40mm" },
      { "Strap Material": "Steel" },
      { Movement: "Automatic" },
      { Condition: "Customised" },
      { "Case Material": "Steel" },
      { Model: "Submariner Date 116610LN 'Hercules Watch Co'" },
      { "Bloombar Ref": "CM885" },
    ],
    images: [
      "/products/Submariner/2019-Rolex-CM885-02.webp",
      "/products/Submariner/2019-Rolex-CM885-03.webp",
      "/products/Submariner/2019-Rolex-CM885-04.webp",
      "/products/Submariner/2019-Rolex-CM885-05.webp",
      "/products/Submariner/2019-Rolex-CM885-06.jpg",
      "/products/Submariner/2019-Rolex-CM885-247.jpg",
      "/products/Submariner/2019-Rolex-CM885-249.jpg",
      "/products/Submariner/2019-Rolex-CM885-251.jpg",
    ],
  },

  {
    id: "6",
    name: "Explorer II 216570 'Hercules Watch Co'",
    price: "£13,995",
    desc: "Presented in excellent condition is this outstanding example of a 2015 Rolex Explorer II 216570, customised by Hercules Watch Co. The watch features a 42mm black DLC coated case, black dial with white luminescent hour markers, black DLC coated bezel and is coupled to a black DLC coated Oyster bracelet. Having been professionally tested for condition and accuracy, it’s deemed to be running perfectly, ready for its new, very lucky owner. The watch is supplied with its original Rolex box, green leather wallet, manuals and swing tag. The watch will be sold with a 36-month Hercules Watch Co warranty from date of sale (Terms & Conditions apply).",
    image:
      "/products/Explorer/Rolex-Explorer-II-216570-Hercules-Watch-Co-CM752-0002-scaled.webp",
    link: "https://bloombarwatches.com/product/rolex-explorer-ii-216570-hercules-watch-co-3/",
    additional: [
      { Box: "Yes" },
      { Papers: "No" },
      { "Case Size": "42mm" },
      { "Strap Material": "Steel (DLC Coated)" },
      { Movement: "Automatic" },
      { Condition: "Customised" },
      { "Case Material": "Steel (DLC Coated)" },
      { Model: "Explorer II 216570 'Hercules Watch Co'" },
      { "Bloombar Ref": "CM752" },
    ],
    images: [
      "/products/Explorer/Rolex-Explorer-II-216570-Hercules-Watch-Co-CM752-0002-scaled.webp",
      "/products/Explorer/Rolex-Explorer-II-216570-Hercules-Watch-Co-CM752-0003-scaled.webp",
      "/products/Explorer/Rolex-Explorer-II-216570-Hercules-Watch-Co-CM752-0004-scaled.webp",
      "/products/Explorer/Rolex-Explorer-II-216570-Hercules-Watch-Co-CM752-0005-scaled.webp",
      "/products/Explorer/Rolex-Explorer-II-216570-Hercules-Watch-Co-CM752-0006-scaled.webp",
      "/products/Explorer/Rolex-Explorer-II-216570-Hercules-Watch-Co-CM752-0007-scaled.webp",
      "/products/Explorer/Rolex-Explorer-II-216570-Hercules-Watch-Co-CM752-0008-scaled.webp",
      "/products/Explorer/Rolex-Explorer-II-216570-Hercules-Watch-Co-CM752-0009-scaled.webp",
    ],
  },

  {
    id: "7",
    name: "Explorer II 216570 'Hercules Watch Co'",
    price: "£17,250",
    desc: "Presented in excellent condition is this stunning example of a 2015 Rolex Explorer II 216570, customised by Hercules Watch Co. The watch features a 42mm black DLC coated case, customised black dial with ‘leather effect’ motif, black DLC coated bezel and is coupled to a black DLC coated Oyster bracelet. Having been professionally tested for condition and accuracy, it’s deemed to be running perfectly, ready for its new, very lucky owner. The watch is supplied with its original Rolex box, green leather wallet, manuals and warranty card dated Q3 2015 (Japan). The watch will be sold with a 36-month Hercules Watch Co warranty from date of sale (Terms & Conditions apply).",
    image:
      "/products/ExplorerII/2015-Rolex-Explorer-II-216570-Hercules-Watch-Co-CM722-0002-scaled.webp",
    link: "https://bloombarwatches.com/product/rolex-explorer-ii-216570-hercules-watch-co-2/",
    additional: [
      { Year: "2015" },
      { Box: "Yes" },
      { Papers: "Yes" },
      { "Case Size": "42mm" },
      { "Strap Material": "Steel (DLC Coated)" },
      { Movement: "Automatic" },
      { Condition: "Customised" },
      { "Case Material": "Steel (DLC Coated)" },
      { Model: "Explorer II 216570 'Hercules Watch Co'" },
      { "Bloombar Ref": "CM722" },
    ],
    images: [
      "/products/ExplorerII/2015-Rolex-Explorer-II-216570-Hercules-Watch-Co-CM722-0002-scaled.webp",
      "/products/ExplorerII/2015-Rolex-Explorer-II-216570-Hercules-Watch-Co-CM722-0003-scaled.webp",
      "/products/ExplorerII/2015-Rolex-Explorer-II-216570-Hercules-Watch-Co-CM722-0004-scaled.webp",
      "/products/ExplorerII/2015-Rolex-Explorer-II-216570-Hercules-Watch-Co-CM722-0005-scaled.webp",
      "/products/ExplorerII/2015-Rolex-Explorer-II-216570-Hercules-Watch-Co-CM722-0006-scaled.webp",
      "/products/ExplorerII/2015-Rolex-Explorer-II-216570-Hercules-Watch-Co-CM722-0009-scaled.webp",
      "/products/ExplorerII/2015-Rolex-Explorer-II-216570-Hercules-Watch-Co-CM722-0010-scaled.webp",
      "/products/ExplorerII/2015-Rolex-Explorer-II-216570-Hercules-Watch-Co-CM722-0011-scaled.webp",
    ],
  },

  {
    id: "8",
    name: "Explorer 36 124273 'Hercules Watch Co'",
    price: "£17,250",
    desc: "This stunning example of a 2022 Rolex Explorer 36 124273 has been customised by Hercules Watch Co and features a 36mm DLC coated stainless steel case, black dial with luminescent hour markers, 18K yellow gold bezel and is coupled to a DLC coated steel & 18K yellow gold Oyster bracelet. Having been professionally tested for condition and accuracy, it’s deemed to be running perfectly, ready for its new, lucky owner. The watch is supplied with its original Rolex box, green leather wallet, manuals, 2x swing tags and warranty card dated Q1 2022. The watch will be sold with a 36-month Hercules Watch Co warranty from date of sale (Terms & Conditions apply).",
    image:
      "/products/Explorer36124273/2022-Rolex-Explorer-124273-Black-DLC-CM681-0002-scaled.webp",
    link: "https://bloombarwatches.com/product/rolex-explorer-36-124273-2/",
    additional: [
      { Year: "2022" },
      { Box: "Yes" },
      { Papers: "Yes" },
      { "Case Size": "36mm" },
      { "Strap Material": "18K Yellow Gold & Steel" },
      { Movement: "Automatic" },
      { Condition: "Customised" },
      { "Case Material": "Steel (DLC Coated)" },
      { Model: "Explorer 36 124273 'Hercules Watch Co'" },
      { "Bloombar Ref": "CM681" },
    ],
    images: [
      "/products/Explorer36124273/2022-Rolex-Explorer-124273-Black-DLC-CM681-0002-scaled.webp",
      "/products/Explorer36124273/2022-Rolex-Explorer-124273-Black-DLC-CM681-0003-scaled.webp",
      "/products/Explorer36124273/2022-Rolex-Explorer-124273-Black-DLC-CM681-0004-scaled.webp",
      "/products/Explorer36124273/2022-Rolex-Explorer-124273-Black-DLC-CM681-0005-scaled.webp",
      "/products/Explorer36124273/2022-Rolex-Explorer-124273-Black-DLC-CM681-0006-scaled.webp",
      "/products/Explorer36124273/2022-Rolex-Explorer-124273-Black-DLC-CM681-0054-scaled.webp",
      "/products/Explorer36124273/2022-Rolex-Explorer-124273-Black-DLC-CM681-0055-scaled.webp",
      "/products/Explorer36124273/2022-Rolex-Explorer-124273-Black-DLC-CM681-0056-scaled.webp",
    ],
  },

  {
    id: "9",
    name: "Explorer II 216570 'Hercules Watch Co'",
    price: "£17,995",
    desc: "Presented in unworn condition is this stealthy example of a 2020 Rolex Explorer II 216570, customised by Hercules Watch Co. The watch features a 42mm black DLC coated case, black ‘Skull’ dial with black/grey hour markers markers, red contrasts, black DLC coated bezel and is coupled to a black DLC coated Oyster bracelet. Having been professionally tested for condition and accuracy, it’s deemed to be running perfectly, ready for its new, very lucky owner. The watch is supplied with its original Rolex box, green leather wallet, manuals, green swing tag and warranty card dated Q2 2020 (UK supplied). The watch will be sold with a 36-month Hercules Watch Co warranty from date of sale (Terms & Conditions apply).",
    image:
      "/products/ExplorerIII/2020-Rolex-Explorer-II-216570-Black-Skull-Hercules-CM703-0002-scaled.webp",
    link: "https://bloombarwatches.com/product/rolex-explorer-ii-216570-hercules-watch-co/",
    additional: [
      { Year: "2020" },
      { Box: "Yes" },
      { Papers: "Yes" },
      { "Case Size": "42mm" },
      { "Strap Material": "Steel" },
      { Movement: "Automatic" },
      { Condition: "Customised" },
      { "Case Material": "Steel" },
      { Model: "Explorer II 216570 'Hercules Watch Co'" },
      { "Bloombar Ref": "CM703" },
    ],
    images: [
      "/products/ExplorerIII/2020-Rolex-Explorer-II-216570-Black-Skull-Hercules-CM703-0002-scaled.webp",
      "/products/ExplorerIII/2020-Rolex-Explorer-II-216570-Black-Skull-Hercules-CM703-0003-scaled.webp",
      "/products/ExplorerIII/2020-Rolex-Explorer-II-216570-Black-Skull-Hercules-CM703-0004-scaled.webp",
      "/products/ExplorerIII/2020-Rolex-Explorer-II-216570-Black-Skull-Hercules-CM703-0005-scaled.webp",
      "/products/ExplorerIII/2020-Rolex-Explorer-II-216570-Black-Skull-Hercules-CM703-0006-scaled.webp",
      "/products/ExplorerIII/2020-Rolex-Explorer-II-216570-Black-Skull-Hercules-CM703-0009-scaled.webp",
      "/products/ExplorerIII/2020-Rolex-Explorer-II-216570-Black-Skull-Hercules-CM703-0010-scaled.webp",
      "/products/ExplorerIII/2020-Rolex-Explorer-II-216570-Black-Skull-Hercules-CM703-0011-scaled.webp",
    ],
  },

  {
    id: "10",
    name: "Air-King 116900 'Hercules Watch Co'",
    price: "£13,495",
    desc: "Presented in unworn condition is this interesting example of a 2018 Rolex Air-King 116900, customised by Hercules Watch Co. The watch features a 40mm black DLC coated stainless steel case, green ‘chameleon’ dial that changes into purple in different angles. This unique timepiece also has a black DLC coated stainless steel bezel, a beautiful exhibition case back and is coupled to a black DLC stainless steel Oyster bracelet. Having been professionally tested for condition and accuracy, it’s deemed to be running perfectly, ready for its new, lucky owner. The watch is supplied with its original Rolex box, green leather wallet, manuals, 2x swing tags and warranty card. The watch will be sold with a 36-month Hercules Watch Co warranty from date of sale (Terms & Conditions apply).",
    image:
      "/products/Air-King116900-2/2018-Rolex-Air-King-116900-Hercules-CM702-0002-scaled.webp",
    link: "https://bloombarwatches.com/product/rolex-air-king-116900-hercules-watch-co/",
    additional: [
      { Year: "2018" },
      { Box: "Yes" },
      { Papers: "Yes" },
      { "Case Size": "40mm" },
      { "Strap Material": "Steel (DLC Coated)" },
      { Movement: "Automatic" },
      { Condition: "Customised" },
      { "Case Material": "Steel (DLC Coated)" },
      { Model: "Air-King 116900 'Hercules Watch Co'" },
      { "Bloombar Ref": "CM702" },
    ],
    images: [
      "/products/Air-King116900-2/2018-Rolex-Air-King-116900-Hercules-CM702-0002-scaled.webp",
      "/products/Air-King116900-2/2018-Rolex-Air-King-116900-Hercules-CM702-0003-scaled.webp",
      "/products/Air-King116900-2/2018-Rolex-Air-King-116900-Hercules-CM702-0004-scaled.webp",
      "/products/Air-King116900-2/2018-Rolex-Air-King-116900-Hercules-CM702-0005-scaled.webp",
      "/products/Air-King116900-2/2018-Rolex-Air-King-116900-Hercules-CM702-0006-scaled.webp",
      "/products/Air-King116900-2/2018-Rolex-Air-King-116900-Hercules-CM702-0007-scaled.webp",
      "/products/Air-King116900-2/2018-Rolex-Air-King-116900-Hercules-CM702-0008-scaled.webp",
      "/products/Air-King116900-2/2018-Rolex-Air-King-116900-Hercules-CM702-0009-scaled.webp",
    ],
  },

  {
    id: "11",
    name: "Submariner Date 116613LN 'Hercules Watch Co'",
    price: "£19,995",
    desc: "This stunning example of a 2015 Rolex Submariner Date 116613LN has been customised by Hercules Watch Co and features a 40mm DLC coated stainless steel case, black dial with white luminescent hour markers, 18K yellow gold bezel with black ceramic insert and is coupled to a DLC coated steel & 18K yellow gold Oyster bracelet. Having been professionally tested for condition and accuracy, it’s deemed to be running perfectly, ready for its new, lucky owner. The watch is supplied with its original Rolex box, green leather wallet, manuals, 2x swing tags and warranty card dated Q2 2015 (UK supplied). The watch will be sold with a 36-month Hercules Watch Co warranty from date of sale (Terms & Conditions apply).",
    image:
      "/products/Submariner116613LN/2015-Rolex-Submariner-Date-116613LN-DLC-Hercules-CM704-0002-scaled.webp",
    link: "https://bloombarwatches.com/product/rolex-submariner-date-116613ln-hercules-watch-co/",
    additional: [
      { Year: "2015" },
      { Box: "Yes" },
      { Papers: "Yes" },
      { "Case Size": "40mm" },
      { "Strap Material": "18K Yellow Gold & Steel" },
      { Movement: "Automatic" },
      { Condition: "Customised" },
      { "Case Material": "Steel" },
      { Model: "Submariner Date 116613LN 'Hercules Watch Co'" },
      { "Bloombar Ref": "CM704" },
    ],
    images: [
      "/products/Submariner116613LN/2015-Rolex-Submariner-Date-116613LN-DLC-Hercules-CM704-0002-scaled.webp",
      "/products/Submariner116613LN/2015-Rolex-Submariner-Date-116613LN-DLC-Hercules-CM704-0003-scaled.webp",
      "/products/Submariner116613LN/2015-Rolex-Submariner-Date-116613LN-DLC-Hercules-CM704-0004-scaled.webp",
      "/products/Submariner116613LN/2015-Rolex-Submariner-Date-116613LN-DLC-Hercules-CM704-0005-scaled.webp",
      "/products/Submariner116613LN/2015-Rolex-Submariner-Date-116613LN-DLC-Hercules-CM704-0006-scaled.webp",
      "/products/Submariner116613LN/2015-Rolex-Submariner-Date-116613LN-DLC-Hercules-CM704-0009-scaled.webp",
      "/products/Submariner116613LN/2015-Rolex-Submariner-Date-116613LN-DLC-Hercules-CM704-0010-scaled.webp",
      "/products/Submariner116613LN/2015-Rolex-Submariner-Date-116613LN-DLC-Hercules-CM704-0011-scaled.webp",
    ],
  },

  {
    id: "12",
    name: "Sea-Dweller 43 126603",
    price: "£21,750",
    desc: "This striking example of a 2021 Rolex Sea-Dweller 126603 has been customised by Hercules Watch Co and features a 43mm DLC coated stainless steel case, black dial with white luminescent hour markers, 18K yellow gold bezel & black ceramic insert and is coupled to a black DLC coated stainless steel & 18K yellow gold Oyster bracelet. Having been professionally tested for condition and accuracy, it’s deemed to be running perfectly, ready for its new, lucky owner. The watch is supplied with its original Rolex box, green leather wallet, manuals, green swing tag and warranty card dated Q2 2021. The watch will be sold with a 36-month Hercules Watch Co warranty from date of sale (Terms & Conditions apply).",
    image:
      "/products/Sea-Dweller43/2021-Rolex-Sea-Dweller-43-126603-Hercules-DLC-CM665-0002-scaled.webp",
    link: "https://bloombarwatches.com/product/rolex-sea-dweller-126603-hercules-watch-co/",
    additional: [
      { Year: "2021" },
      { Box: "Yes" },
      { Papers: "Yes" },
      { "Case Size": "43mm" },
      { "Strap Material": "18K Yellow Gold & Steel" },
      { Movement: "Automatic" },
      { Condition: "Customised" },
      { "Case Material": "Steel" },
      { Model: "Sea-Dweller 43 126603" },
      { "Bloombar Ref": "CM665" },
    ],
    images: [
      "/products/Sea-Dweller43/2021-Rolex-Sea-Dweller-43-126603-Hercules-DLC-CM665-0002-scaled.webp",
      "/products/Sea-Dweller43/2021-Rolex-Sea-Dweller-43-126603-Hercules-DLC-CM665-0003-scaled.webp",
      "/products/Sea-Dweller43/2021-Rolex-Sea-Dweller-43-126603-Hercules-DLC-CM665-0004-scaled.webp",
      "/products/Sea-Dweller43/2021-Rolex-Sea-Dweller-43-126603-Hercules-DLC-CM665-0005-scaled.webp",
      "/products/Sea-Dweller43/2021-Rolex-Sea-Dweller-43-126603-Hercules-DLC-CM665-0006-scaled.webp",
      "/products/Sea-Dweller43/2021-Rolex-Sea-Dweller-43-126603-Hercules-DLC-CM665-0045-scaled.webp",
      "/products/Sea-Dweller43/2021-Rolex-Sea-Dweller-43-126603-Hercules-DLC-CM665-0046-scaled.webp",
      "/products/Sea-Dweller43/2021-Rolex-Sea-Dweller-43-126603-Hercules-DLC-CM665-0047-scaled.webp",
    ],
  },

  {
    id: "13",
    name: "GMT-Master II 116713LN",
    price: "£19,995",
    desc: "This eye-catching example of a Rolex GMT-Master II 116713LN has been customised by Hercules Watch Co and features a 40mm DLC coated stainless steel case, black dial with white luminescent hour markers, 18K yellow gold bezel with black ceramic insert and is coupled to a DLC coated steel & 18K yellow gold Oyster bracelet. Having been professionally tested for condition and accuracy, it’s deemed to be running perfectly, ready for its new, lucky owner. The watch is supplied with its original Rolex box, green leather wallet, manuals and warranty card (UK supplied, un-dated). The watch will be sold with a 36-month Hercules Watch Co warranty from date of sale (Terms & Conditions apply).",
    image:
      "/products/GMT-Master/Rolex-GMT-Master-II-1166713LN-Hercules-DLC-CM664-0002-scaled.webp",
    link: "https://bloombarwatches.com/product/rolex-gmt-master-ii-116713ln-hercules-watch-co/",
    additional: [
      { Year: "Approx. 2015" },
      { Box: "Yes" },
      { Papers: "Yes" },
      { "Case Size": "40mm" },
      { "Strap Material": "18K Yellow Gold & Steel" },
      { Movement: "Automatic" },
      { Condition: "Customised" },
      { "Case Material": "Steel (DLC Coated)" },
      { Model: "GMT-Master II 116713LN" },
      { "Bloombar Ref": "CM664" },
    ],
    images: [
      "/products/GMT-Master/Rolex-GMT-Master-II-1166713LN-Hercules-DLC-CM664-0002-scaled.webp",
      "/products/GMT-Master/Rolex-GMT-Master-II-1166713LN-Hercules-DLC-CM664-0003-scaled.webp",
      "/products/GMT-Master/Rolex-GMT-Master-II-1166713LN-Hercules-DLC-CM664-0004-scaled.webp",
      "/products/GMT-Master/Rolex-GMT-Master-II-1166713LN-Hercules-DLC-CM664-0005-scaled.webp",
      "/products/GMT-Master/Rolex-GMT-Master-II-1166713LN-Hercules-DLC-CM664-0006-scaled.webp",
      "/products/GMT-Master/Rolex-GMT-Master-II-1166713LN-Hercules-DLC-CM664-0041-scaled.webp",
      "/products/GMT-Master/Rolex-GMT-Master-II-1166713LN-Hercules-DLC-CM664-0042-scaled.webp",
      "/products/GMT-Master/Rolex-GMT-Master-II-1166713LN-Hercules-DLC-CM664-0043-scaled.webp",
    ],
  },
];

export default collections;
